### ISSUE TITLE
Error no attribute 'imread'

### ISSUE THREAD

**Issue by adriandegonda** [shellerbrand/machine-learning-for-artistic-style#1]
'''
Wollte soeben das Tool ausprobieren. Hat alles bis zur Umwandlung funktioniert. Diese dann leider nicht mehr... Colab von Google verwendet
Wäre toll zu erfahren, was ich falsch gemacht habe / ob ein Fehler behoben worden ist. 
'''
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-3021bf5d04d8> in <module>()
     13 
     14 with tf.device('/gpu:0'):
---> 15   arbitrary_stylization_with_weights(c)
     16 
     17 print("\nErledigt.")

1 frames
/content/lib/image_utils.py in load_np_image_uint8(image_file)
    411         f.write(tf.gfile.GFile(image_file, 'rb').read())
    412         f.flush()
--> 413         image = scipy.misc.imread(f.name)
    414         # Workaround for black-and-white images
    415         if image.ndim == 2:

AttributeError: module 'scipy.misc' has no attribute 'imread'

**Comment by shellerbrand** [comment]
Das Problem rührt daher, dass die Style-Transfer Bibliothek die Funktion 'imread' in der neueren Version der Bibliothek scipy nicht mehr findet, die inzwischen standardmäßig in Colaboratory benutzt wird. Ich habe nun einen Versionsdowngrade forciert.

commit e9a85f18b81aad59c87fe33d6865039204916426

Viele Grüße
Stephan

**Comment by adriandegonda** [comment]
Funktioniert!
Vielen Dank für die superschnelle Hilfe. 
Liebe Grüsse
Adrian
